services:
  frontend:
    # Construye la imagen desde el Dockerfile en el contexto actual
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    # Configura el healthcheck para asegurar que el servicio esté listo antes de ejecutar pruebas
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      retries: 5
      start_period: 30s
